kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: camel-leader-election
subjects:
- kind: ServiceAccount
  name: camel-leader-election
roleRef:
  kind: Role
  name: camel-leader-election
  apiGroup: rbac.authorization.k8s.io
