kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: camel-leader-election
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - pods
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
